---
#################################
#     CONNECTION VARIABLES      #
#################################

ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios
ansible_become: yes
ansible_become_method: enable
ansible_user: admin
ansible_ssh_password: "C1sco12345"